substitutions:
  devicename: 3ddrucker_cam
  sensorname: 3ddrucker_cam
  wifi_ip: "172.18.18.71"

packages:
  #Include common definitions for home (wifi, web server, etc)
  settings: !include settings/common.yaml

esphome:
  name: ${devicename}
  platform: ESP32
  board: node32s
  build_path: build/${devicename}

esp32_camera:
  external_clock:
    pin: GPIO0
    frequency: 20MHz
  i2c_pins:
    sda: GPIO26
    scl: GPIO27
  data_pins: [GPIO5, GPIO18, GPIO19, GPIO21, GPIO36, GPIO39, GPIO34, GPIO35]
  vsync_pin: GPIO25
  href_pin: GPIO23
  pixel_clock_pin: GPIO22
  power_down_pin: GPIO32

  
    # Image settings
  name: ${devicename}
  max_framerate: 10 fps
  resolution: 800x600
  jpeg_quality: 20
  idle_framerate: 0.2 fps
#  contrast: 2
#  saturation: 2

output:
#flashlight
  - platform: gpio
    pin: GPIO4
    id: gpio_4
#statuslight
  - platform: gpio
    pin:
      number: GPIO33
      inverted: True
    id: gpio_33
light:
#flashlight
  - platform: binary
    output: gpio_4
    name: devicename flash
#statuslight
  - platform: binary   
    output: gpio_33
    name: devicename status
    
    
    
sensor:
  - platform: wifi_signal
    name: devicename WiFi Signal
    update_interval: 60s
  - platform: uptime
    name: devicename Uptime

    
text_sensor:
  - platform: version
    name: devicename ESPHome Version
  - platform: wifi_info
    ssid:
      name: devicename WiFi

switch:      
  - platform: restart
    name: devicename restart
    
binary_sensor:
  - platform: status
    name: devicename status
    
#esp32_camera:
#  name: ${devicename}
#  external_clock:
#    pin: GPIO0
#    frequency: 20MHz
#  i2c_pins:
#    sda: GPIO26
#    scl: GPIO27
#  data_pins: [GPIO5, GPIO18, GPIO19, GPIO21, GPIO36, GPIO39, GPIO34, GPIO35]
#  vsync_pin: GPIO25
 # href_pin: GPIO23
 # pixel_clock_pin: GPIO22
#  power_down_pin: GPIO32
  # Image settings
  #max_framerate: 5 fps    # default: 10 fps, max 60
  #idle_framerate: 0.2 fps # default: 0.1 fps - framerate for 'picture' in HA dashboard
  #resolution: 800x600     # default: 640x480 (VGA) - higher res requires more memory
  #jpeg_quality: 10        # 10 (best) to 63 (worst)

#switch:
#  - platform: gpio
#    name: "${devicename} flash"
#    pin: 4
    #inverted: True
#  - platform: restart
#    name: "${devicename} - Restart"
#    id: restart_switch