substitutions:
  devicename: hwr
  sensorname: hwr
  wifi_ip: "172.18.18.75"

packages:
  #Include common definitions for home (wifi, web server, etc)
  settings: !include settings/common.yaml

esphome:
  name: ${devicename}
  platform: ESP8266
  board: d1_mini
  #arduino_version: 2.4.2
  build_path: build/${devicename}

dallas:
  - pin: GPIO2