substitutions:
  devicename: hwr
  sensorname: hwr
  wifi_ip: "172.18.18.75"

packages:
  #Include common definitions for home (wifi, web server, etc)
  settings: !include settings/common.yaml

esphome:
  name: ${devicename}
  platform: ESP8266
  board: d1_mini
  #arduino_version: 2.4.2
  build_path: build/${devicename}

dallas:
  - pin: GPIO2

sensor:
# Stromzähler als Pulse Meter
  #- platform: pulse_meter
  - platform: pulse_counter
    name: "Stromverbrauch"
    unit_of_measurement: "kW"
    pin:
      number: GPIO4
      mode: INPUT_PULLUP
    update_interval: 60s
    filters:
      - multiply: 0.012 # in KW
    #  - multiply: 6 # in W
    accuracy_decimals: 3
    icon: 'mdi:flash'
    id: energieverbrauch_kw
    #accuracy_decimals: 3
    #timeout: 2 min
    #id: energieverbrauch_w
    #filters:
      # Filter outliers
    #  - median:
    #      window_size: 3
    #      send_every: 1
    #      send_first_at: 1
      # Convert pulses/min to kW bei 10000Imp/kWh
     # - multiply: 0.006
    total:
      name: "Stromzähler"
      unit_of_measurement: "kWh"
      accuracy_decimals: 3
      filters:
        - multiply: 0.0001
  # Dieser Sensor errechnet die Wh aus den aktuellen Verbrauchswerten in W  
  - platform: total_daily_energy
    name: "Tagesverbrauch"
    power_id: energieverbrauch_kw
    #restore: false
  - platform: dallas
    address: 0x6f02201018441a28
    name: "Nuc_temp"
  - platform: dallas
    address: 0xfe0220100cd93728
    name: "Serverschrank_temp"
time:
  - platform: sntp
    id: my_time