wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  manual_ip:
    static_ip: ${wifi_ip}
    gateway: !secret wifi_gateway
    subnet: !secret wifi_subnet
    dns1: !secret wifi_dns1

  ap:
    ssid: !secret wifi_ap_ssid
    password: !secret wifi_ap_password

# Enable Home Assistant API
api:
  reboot_timeout: 0s
  #password: !secret api_password
  encryption:
    key: !secret api_enc_key

ota:
  password: !secret ota_password

logger:
  #level: VERY_VERBOSE
  #level: INFO

web_server:
  port: 80

time:
  - platform: homeassistant

sensor:
  - platform: uptime
    name: ${sensorname} Uptime
    filters:
      - lambda: return x / 3600.0;
    unit_of_measurement: "hours"
    accuracy_decimals: 2
    update_interval: !secret uptime_update_interval